# Tell Mongoid which environment this configuration is for.
production:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
  # Here we put the Mongoid specific configuration options. These are explained
  # in more detail next.
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    # Note this can also be true if you want to preload everything, but this is
    # almost never necessary. Most of the time set this to false.
    preload_models:
      - TeamMember
      - Department
    scope_overwrite_exception: true
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true

# Tell Mongoid which environment this configuration is for.
development:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      uri: 'mongodb://localhost/mongo_dev'
  # Here we put the Mongoid specific configuration options. These are explained
  # in more detail next.
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    # Note this can also be true if you want to preload everything, but this is
    # almost never necessary. Most of the time set this to false.
    preload_models:
      - TeamMember
      - Department
    scope_overwrite_exception: true
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true

# Tell Mongoid which environment this configuration is for.
test:
  # This starts the session configuration settings. You may have as
  # many sessions as you like, but you must have at least 1 named
  # 'default'.
  sessions:
    # Define the default session.
    default:
      uri: 'mongodb://localhost/mongo_test'
  # Here we put the Mongoid specific configuration options. These are explained
  # in more detail next.
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    # Note this can also be true if you want to preload everything, but this is
    # almost never necessary. Most of the time set this to false.
    preload_models:
      - TeamMember
      - Department
    scope_overwrite_exception: true
    skip_version_check: false
    use_activesupport_time_zone: false
    use_utc: true